from __future__ import annotations

from math import inf

APP_NAME = "temptamer"
LOGGER_NAME = "pyscript.temptamer"

COMFORT_MODE_OFF = "Off"
COMFORT_MODE_NIGHT = "Night"
COMFORT_MODE_DAY = "Day"
COMFORT_MODE_OFFICE = "Office"
COMFORT_MODE_AUTO = "Auto"

CONTROL_HVAC_MODE_HEAT = "Heat"
CONTROL_HVAC_MODE_COOL = "Cool"
CONTROL_HVAC_MODE_HEATCOOL = "HeatCool"
CONTROL_HVAC_MODE_OFF = "Off"
CONTROL_HVAC_MODE_MANUAL = "Manual"

SCHEME_OFF = "Off"
SCHEME_NIGHT = "Night"
SCHEME_DAY_LIVING = "DayLiving"
SCHEME_DINING_BASIC = "DiningBasic"
SCHEME_BEDROOM = "Bedroom"
SCHEME_BATHROOM = "Bathroom"

UNKNOWN_STATES = frozenset({"", "none", "unknown", "unavailable"})
SWITCH_ON_STATES = frozenset({"on", "open", "true", "1"})
FAN_LOW = "low"
FAN_MEDIUM = "medium"
HVAC_HEAT = "heat"
HVAC_COOL = "cool"
HVAC_FAN_ONLY = "fan_only"
HVAC_OFF = "off"

CONTROL_INTERVAL_SECONDS = 60
MIN_ZONE_HOLD_SECONDS = 10 * 60
MIN_ZONE_CHANGE_DELAY_SECONDS = 5 * 60
SWITCH_STATE_SETTLE_SECONDS = CONTROL_INTERVAL_SECONDS * 2
MIN_HEAT_COOL_TRANSITION_SECONDS = 60 * 60
MIN_IDLE_SECONDS = 60 * 60
IDLE_HEAT_STAGE_1_SECONDS = 2 * 60
IDLE_HEAT_STAGE_2_SECONDS = 5 * 60
IDLE_HEAT_STAGE_3_SECONDS = 9 * 60
IDLE_HEAT_STAGE_4_SECONDS = 15 * 60
IDLE_HEAT_STAGE_5_SECONDS = 20 * 60
IDLE_HEAT_STAGE_6_SECONDS = 25 * 60
IDLE_HEAT_UNWIND_SECONDS = 10 * 60
IDLE_HEAT_RESTART_MEMORY_SECONDS = 30 * 60
MIN_OPEN_ZONES = 1
MAX_DISCRETIONARY_ZONE_CHANGES_PER_PASS = 1

HEAT_START_MEDIUM_FAN_DIFFERENTIAL = 3.0
LOW_TO_MEDIUM_FAN_DIFFERENTIAL = 4.0
MEDIUM_TO_LOW_FAN_DIFFERENTIAL = 2.0

IDLE_HEAT_STEP_1_DELTA = 1.0
IDLE_HEAT_STEP_2_DELTA = 2.0
IDLE_HEAT_STEP_3_DELTA = 3.0
IDLE_HEAT_STEP_4_DELTA = 4.0
IDLE_HEAT_STEP_5_DELTA = 5.0
IDLE_HEAT_STEP_6_DELTA = 6.0
IDLE_HEAT_STEP_7_DELTA = 7.0
IDLE_HEAT_STEP_11_DELTA = 11.0
INITIAL_IDLE_HEAT_GAP_THRESHOLD = 2.0
INITIAL_IDLE_HEAT_BLEND_FACTOR = 0.5
MIN_HEAT_SETPOINT = 17
MAX_HEAT_SETPOINT = 25

OFF_TEMPERATURE = -inf
